plugins:
  - react
extends:
  - airbnb
parser: babel-eslint
parserOptions:
    ecmaVersion: 7
    sourceType: module
    ecmaFeatures:
      experimentalObjectRestSpread: true
      jsx: true
env:
    es6: true
    browser: true
    node: true
settings:
  import/resolver: webpack
